### PR TITLE
Add EvictingOkanshiMonitorRegistry

### PR DESCRIPTION
**Pull request by kbilsted**
An attempt at an evicting registry. What do you think? I have not made any tests before we agree on an implementation.

### CODE REVIEW

**Comment by kbilsted** [comment]
I wanted to use inheritance but F# does not have `protected` access modifier and I did not want to expose the internal `monitors` variable.

**Comment by kbilsted** [comment]
Notice this is a very simple mechanism, but it has a very low overhead compared to making a counter pr. monitor and changing each counter on pull.

**Comment by kbilsted** [comment]
Yea i fully agree. Hence the documentation for the class. Is there another way if you evict?

**Comment by kbilsted** [comment]
Ah not well documented. It can also log the monitors it evicts so you have a chance to see whats going on.

**Comment by kichristensen** [comment]
Why not use the absent filter and only evict monitors that haven't received data for a while?

**Comment by kbilsted** [comment]
We can do. But it does not solve theproblem you mentioned where monitors are stored in local variables. 
All it does is save some monitor instantiations. Not sure how many since eviction wont happen often (eg only every 2minutes)

Also, how will the registry work? Will it have a monitor factory in its belly and wrap all instances upon regiatering a monitor ? How will it work with 3rd monitors party monitors we do not know about and thus are not wrapped ?

**Comment by kichristensen** [comment]
You are right it won't solve the problem with monitors stored in local variables. The main problem is that we don't know when a monitor is no longer used. Would it help adding `Dispose` to all monitors? I'm not sure as monitors don't know which registry the are registered in.

**Comment by kbilsted** [comment]
I think the issue revolves around black box monitoring. So perhaps we should confine the functionality but still make it available.

**Comment by kbilsted** [comment]
A dispose method is not a bad idea. Then each .monitor  can be configured to either log or throw exception if they are used after eviction. 

It will cost an if check on each monitor registration however. But with cpu branch prediction this may not be measurable at all.

I think it's better than hiding dangerous functionality behind an obscurenamespace

**Comment by kichristensen** [comment]
I think implementing `IDisposable` on monitors with a `WeakReference` to the registry could be a good solution, but I haven't tried it, so there might be some issues I haven't thought about

**Comment by kbilsted** [comment]
Can we merge this? :-)

**Comment by kichristensen** [comment]
It doesn't seem like we have found the right design to solve this issue, which is why I think it would make sense to have this as a separate package and not part of the core, until we have the solution design covered

**Pull request closed without merging**
