### PR TITLE
Describe HealthCheck as monitor

### LINKED ISSUE #76: document healthcheck as monitor
in the tutorial it states

> As of version 4 health checks can also be registered as a monitor. This is done like this:

please explain the difference to using the monitor and the health check. Both seem to be a func -> bool

### PR DESCRIPTION
**Pull request by kichristensen**
Explain the differences when registering HealthChecks as a monitor.
closes #76

### CODE REVIEW

**Comment by kbilsted** [comment]
Im still not sure in which situations I want a healthcheck and when I want it as a monitor. The monitor example isn't that the same as a normal gauge?  Before this monitor example healthcheck was a simple concept to grasp and understand.

**Comment by kichristensen** [comment]
Maybe the static HealthCheck part should be moved to the endpoint, as it has no effect in other situations.
Yes the monitor is basically just a Gauge with a boolean value, so it could just be deleted, and people could just use a gauge directly

**Comment by kbilsted** [comment]
Ok I'd write that explanation in the tutorial. Or really, if I may have a say, I'd prefer to delete the code and have people use the Gauge. It makes the concepts much simpler

**Comment by kbilsted** [comment]
Can I have the satisfaction of deleting it? ;-)

**Comment by kichristensen** [comment]
Sure

**Pull request closed without merging**
