### PR TITLE
Add SlaTimer

### PR DESCRIPTION
**Pull request by kbilsted**
just the code. Documentation will follow when we can agree on the code ;)

### CODE REVIEW

**Comment by kbilsted** [comment]
hvorfor er det jeg ikke kan få ctor overload til at fungere? jeg gider ikke skrive

 ` timer = new Timer(MonitorConfig.Build("Test"), () => stopwatch, "");`

**Comment by kichristensen** [comment]
When would you use this monitor? Why choose this over processing the values, after they are stored somewhere?

**Comment by kbilsted** [comment]
I would use this monitor when I know I have explicit SLA's in my system and I need to identify when they happen. The SLA is pr. request and not an aggregated value that the existing `Timer` provide

**Comment by kichristensen** [comment]
Good point about the aggregation. Why do you want to store both the request below and above the SLA?

**Comment by kbilsted** [comment]
> 
> 
> Good point about the aggregation. Why do you want to store both the request below and above the SLA?

Fair question. My thinking was a few scenarios

1. if it goes bad, how bad is it
2. if we are within SLA - how close are we to the threshold
3. I want some "historical facts" - I would guess often the SLA breach happens in periods, and I want to be able to understand how a "normal" day looks like in comparison to when it goes bad.

**Comment by kbilsted** [comment]
tests are failing. is it related to my code? i dont have access to see the error

**Comment by kichristensen** [comment]
I've restarted the build is has nothing to do with you

**Comment by kbilsted** [comment]
> Just move the line to the SlaTimer type

I cannot get the compiler to accept that change.

**Comment by kichristensen** [comment]
> 
> 
> > Just move the line to the SlaTimer type
> 
> I cannot get the compiler to accept that change.

I've pushed the necessary change to your branch

**Comment by kichristensen** [comment]
@kbilsted yes it would make sense to rename it

**Comment by kbilsted** [comment]
Done

**Comment by kichristensen** [comment]
LGTM, please add some documentation and update the changelog, then it can be merged

**Comment by kbilsted** [comment]
forgot changelog

**Pull request merged**
