### PR TITLE
Add monitor filters

### PR DESCRIPTION
**Pull request by kbilsted**

### CODE REVIEW

**Comment by kichristensen** [comment]
Looks good, but you have the rebase on master before it can be merged

**Comment by kichristensen** [comment]
Yes that is correct, you can no combine it with OkanshiMonitor. You have to create a monitor manually before passing it in, or you extend OkanshiMonitor with the wrapping methods

**Comment by kbilsted** [comment]
So how do we proceed?

We could extend okanshimonitor with a `WithFilter` eg

    OkanshiMonitor.WithZeroFilter().Counter("c")

become


        let config = MonitorConfig.Build(name).WithTags(OkanshiMonitor.DefaultTags).WithTags(tags)
        monitorRegistry.GetOrAdd(config, fun x -> xxxFilter(new MaxGauge(x)))



Im not sure we can prevent the following (which I think is ok)

    OkanshiMonitor.Counter("c")
    OkanshiMonitor.WithZeroFilter().Counter("c")

which creates two monitors with the same name but different filtering


Finally, the filters do not take a `MonitorConfig` in the ctor - all the monitors do that - so should the filters do the same?

**Comment by kbilsted** [comment]
It seems like we need to change the poller `MetricMonitorRegistryPoller` as well as it sends data to the observer irregardless of any data in the monitor

**Comment by kbilsted** [comment]
So you want me to revert so observers are always called ?

**Comment by kbilsted** [comment]
So you want me to revert so observers are always called ? The influx observer doesn't check if values is empty either..

**Comment by kbilsted** [comment]
So you want me to revert so observers are always called ? The influx observer doesn't check if values is empty either..

**Pull request merged**
