### PR TITLE
reduce allocations on get values

### PR DESCRIPTION
**Pull request by kbilsted**

### CODE REVIEW

**Comment by kichristensen** [comment]
How do this avoid allocations? Has it been verified by a profiler?

**Comment by kbilsted** [comment]
The seq is an allocation and the first call also incur an overhead. Also this pr is part of a secret plan to get rid of all those lazy collections you are making eager by calling tolist on them.. ;)

**Comment by kbilsted** [comment]
So should I change GetValueAs to internal? Or scrap altogether?

I thought your idea was that most of the api was supposed to be public?

**Comment by kichristensen** [comment]
After taking a close look you could remove the mapping part in the timer.
And in the gauge you could remove the conversion between seq and list and you would get the same result. But only remove the converstion between seq and list for GetValues, not for GetValuesAndReset as it is important that it's being evaluated at the right time in GetValuesAndReset

**Comment by kbilsted** [comment]
We just need to be careful with code that is brittle and difficult to see you are changing in the wrong way. But I sense you don't like the `GetValueAs()`. In that case just close the PR

**Pull request closed without merging**
