### PR TITLE
Pr separate out nongenerated docs

### PR DESCRIPTION
**Pull request by kbilsted**
moved documentation to version specific folders and added syntax coloring

### CODE REVIEW

**Comment by kichristensen** [comment]
Have you tried to generate the documentation and see if the links still work?

**Comment by kbilsted** [comment]
not sure there is more than 1 link ?

**Comment by kichristensen** [comment]
Do we want links from the website to tutorial outside the website? I can see pros and cons for each

**Comment by kbilsted** [comment]
What are the pro and cons?

**Comment by kichristensen** [comment]
Accepted as is, but in the future it should be part of the website too. But until it has been improved this way is better

**Pull request merged**
