### PR TITLE
example implementation

### PR DESCRIPTION
**Pull request by kbilsted**
is this how we want to implement this feature for https://github.com/mvno/Okanshi/issues/104 ?

### CODE REVIEW

**Comment by kichristensen** [comment]
How would you this work with monitors with multiple values?
I'm not sure I like the proposed way, but I don't have any good suggestions either. That's why I ask

**Comment by kbilsted** [comment]
It's a dictionary so you can map many names

**Comment by kichristensen** [comment]
Yes, but right in the example you mapping using the hardcoded value "value", could you so an example for for example `Timer`

**Comment by kbilsted** [comment]
example committed

**Comment by kichristensen** [comment]
So this fully relies on "magic" values to specify customized names? Can we really not come up with a better solution? It seems like we are switching one type of magic strings with another type.

**Comment by kbilsted** [comment]
Perhaps we can introduce constants for each of the "magic" names defined in each monitor?

**Comment by kichristensen** [comment]
I think we need to design this a bit more. I'll close this PR, as I think we should move the discussion to an issue instead

**Pull request closed without merging**
